export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_LOGIN_ERROR = 'CREATE_ARTICLE_ERROR';
export const CREATE_REGISTER_ERROR = 'CREATE_REGISTER_ERROR';

export const POST_LOADING = 'POST_LOADING';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const UPDATE_USER_POST = 'UPDATE_USER_POST';
export const EDIT_POST = 'EDIT_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const DELETE_POST = 'DELETE_POST';
export const CLEAR_POSTS = 'CLEAR_POSTS';

export const ADD_CHAT = 'ADD_CHAT';
export const GET_CHAT = 'GET_CHAT';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const AFTER_POST_MESSAGE = 'AFTER_POST_MESSAGE';

export const SUBSCRIPTION_LOADING = 'SUBSCRIPTION_LOADING';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';

export const USER_LOADING = 'USER_LOADING';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
